### ISSUE TITLE
'LogoutView' object has no attribute 'get_serializer_class'

### ISSUE THREAD

**Issue by omidraha** [marcgibbons/django-rest-swagger#483]
Use `django-rest-swagger` with [django-rest-auth](https://github.com/Tivix/django-rest-auth) caused to raise this error:
```
'LogoutView' object has no attribute 'get_serializer_class'
```
```
/rest_framework/schemas.py in get_serializer_fields
            request body input, as determined by the serializer class.
            """
            if method not in ('PUT', 'PATCH', 'POST'):
                return []
            fields = []
                        serializer_class = view.get_serializer_class()
            serializer = serializer_class()
            if isinstance(serializer, serializers.ListSerializer):
                return coreapi.Field(name='data', location='body', required=True)
            if not isinstance(serializer, serializers.Serializer):
```
The `LogoutView` on the `django-rest-auth` module is a normal APIView:
```
class LogoutView(APIView):

    """
    Calls Django logout method and delete the Token object
    assigned to the current User object.

    Accepts/Returns nothing.
    """
    permission_classes = (AllowAny,)

    def post(self, request):
        try:
            request.user.auth_token.delete()
        except (AttributeError, ObjectDoesNotExist):
            pass

        logout(request)

        return Response({"success": _("Successfully logged out.")},
                        status=status.HTTP_200_OK)


```

requirements.txt
```
...
djangorestframework==3.4.0
django-rest-swagger==2.0.1
django-rest-auth==0.7.0
```
settings.py
```
INSTALLED_APPS = (
    ...
    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'rest_framework_swagger',
)
```
urls.py
```
...
from rest_framework.decorators import api_view, renderer_classes
from rest_framework import response, schemas
from rest_framework_swagger.renderers import OpenAPIRenderer, SwaggerUIRenderer

@api_view()
@renderer_classes([OpenAPIRenderer, SwaggerUIRenderer])
def schema_view(request):
    generator = schemas.SchemaGenerator(title='Bookings API')
    return response.Response(generator.get_schema(request=request))


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^docs/', schema_view),
]
```

**Comment by marcgibbons** [comment]
@omidraha Thank you for reporting this. Linking issue https://github.com/tomchristie/django-rest-framework/issues/4265

**Comment by tomchristie** [comment]
Resolved in 3.4.1.

**Comment by marcgibbons** [comment]
Great! Closing this out.

**Comment by angvp** [comment]
is not resolved I don't know how you do your tests. but this is still broken.
