### ISSUE TITLE
deploy on heroku gives "Error: could not determine PostgreSQL version from '10.1'"

### ISSUE THREAD

**Issue by GabLeRoux** [marcgibbons/django-rest-swagger#741]
I tried the following example:
https://heroku.com/deploy?template=https://github.com/marcgibbons/django-rest-swagger

but `master` seem to have an outdated version of `psycopg2` which fails to detect latest postgresql version:

```
-----> Python app detected

 !     The latest version of Python 3 is python-3.6.4 (you are using python-3.6.0, which is unsupported).

 !     We recommend upgrading by specifying the latest version (python-3.6.4).

       Learn More: https://devcenter.heroku.com/articles/python-runtimes

-----> Installing python-3.6.0

-----> Installing pip

-----> Installing requirements with pip

       Collecting Django==1.10.6 (from -r /tmp/build_b6e0e5d855348ffaa37b1430ee5592d1/marcgibbons-django-rest-swagger-71a4cbd/requirements.txt (line 1))

         Downloading Django-1.10.6-py2.py3-none-any.whl (6.8MB)

       Collecting djangorestframework==3.6.0 (from -r /tmp/build_b6e0e5d855348ffaa37b1430ee5592d1/marcgibbons-django-rest-swagger-71a4cbd/requirements.txt (line 2))

         Downloading djangorestframework-3.6.0-py2.py3-none-any.whl (1.2MB)

       Collecting coreapi==2.3.0 (from -r /tmp/build_b6e0e5d855348ffaa37b1430ee5592d1/marcgibbons-django-rest-swagger-71a4cbd/requirements.txt (line 3))

         Downloading coreapi-2.3.0.tar.gz

       Collecting openapi-codec==1.3.1 (from -r /tmp/build_b6e0e5d855348ffaa37b1430ee5592d1/marcgibbons-django-rest-swagger-71a4cbd/requirements.txt (line 4))

         Downloading openapi-codec-1.3.1.tar.gz

       Collecting simplejson==3.9.0 (from -r /tmp/build_b6e0e5d855348ffaa37b1430ee5592d1/marcgibbons-django-rest-swagger-71a4cbd/requirements.txt (line 5))

         Downloading simplejson-3.9.0.tar.gz (77kB)

       Collecting tox==2.4.1 (from -r /tmp/build_b6e0e5d855348ffaa37b1430ee5592d1/marcgibbons-django-rest-swagger-71a4cbd/requirements.txt (line 8))

         Downloading tox-2.4.1-py2.py3-none-any.whl (41kB)

       Collecting pylint==1.6.4 (from -r /tmp/build_b6e0e5d855348ffaa37b1430ee5592d1/marcgibbons-django-rest-swagger-71a4cbd/requirements.txt (line 9))

         Downloading pylint-1.6.4-py2.py3-none-any.whl (569kB)

       Collecting coverage==4.2 (from -r /tmp/build_b6e0e5d855348ffaa37b1430ee5592d1/marcgibbons-django-rest-swagger-71a4cbd/requirements.txt (line 10))

         Downloading coverage-4.2.tar.gz (359kB)

       Collecting ipdb==0.10.1 (from -r /tmp/build_b6e0e5d855348ffaa37b1430ee5592d1/marcgibbons-django-rest-swagger-71a4cbd/requirements.txt (line 11))

         Downloading ipdb-0.10.1.tar.gz

       Collecting mkdocs==0.15.3 (from -r /tmp/build_b6e0e5d855348ffaa37b1430ee5592d1/marcgibbons-django-rest-swagger-71a4cbd/requirements.txt (line 14))

         Downloading mkdocs-0.15.3-py2.py3-none-any.whl (966kB)

       Collecting dj_database_url==0.4.1 (from -r /tmp/build_b6e0e5d855348ffaa37b1430ee5592d1/marcgibbons-django-rest-swagger-71a4cbd/requirements.txt (line 17))

         Downloading dj-database-url-0.4.1.tar.gz

       Collecting psycopg2==2.6.2 (from -r /tmp/build_b6e0e5d855348ffaa37b1430ee5592d1/marcgibbons-django-rest-swagger-71a4cbd/requirements.txt (line 18))

         Downloading psycopg2-2.6.2.tar.gz (376kB)

           Complete output from command python setup.py egg_info:

           running egg_info

           creating pip-egg-info/psycopg2.egg-info

           writing pip-egg-info/psycopg2.egg-info/PKG-INFO

           writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt

           writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt

           writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'

           Error: could not determine PostgreSQL version from '10.1'

           

           ----------------------------------------

       Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-nul9mjr5/psycopg2/

 !     Push rejected, failed to compile Python app.

 !     Push failed
```

Solution would be to upgrade psycopg2 requirement.

**Comment by GabLeRoux** [comment]
This error is fixed with `psycopg2==2.7.1`.

**Comment by rsedger** [comment]
I have psycopg2==2.7.4 and still get this error - any advice?

**Comment by GabLeRoux** [comment]
@rsedger 
Well on my side, it worked with `psycopg2==2.7.1` as shown with #742. I just tried again and it works. You can try the link in #742. Could it be a regression with 2.7.4? Fork the repo and try with your link and paste output here.

**Comment by rsedger** [comment]
Hi Gab, thanks for your response. Actually I'm trying to build a different app on Heroku (the MDN Django Tutorial LocalLibrary app). Here's the last build output:

`-----> Python app detected
-----> Installing python-3.6.4
-----> Installing pip
-----> Installing requirements with pip
       Collecting dj-database-url==0.4.2 (from -r /tmp/build_3be992cc7305a5f64b18851311e565f2/requirements.txt (line 1))
         Downloading dj_database_url-0.4.2-py2.py3-none-any.whl
       Collecting Django==2.0.2 (from -r /tmp/build_3be992cc7305a5f64b18851311e565f2/requirements.txt (line 2))
         Downloading Django-2.0.2-py3-none-any.whl (7.1MB)
       Collecting gunicorn==19.7.1 (from -r /tmp/build_3be992cc7305a5f64b18851311e565f2/requirements.txt (line 3))
         Downloading gunicorn-19.7.1-py2.py3-none-any.whl (111kB)
       Collecting psycopg2==2.6.2 (from -r /tmp/build_3be992cc7305a5f64b18851311e565f2/requirements.txt (line 4))
         Downloading psycopg2-2.6.2.tar.gz (376kB)
           Complete output from command python setup.py egg_info:
           running egg_info
           creating pip-egg-info/psycopg2.egg-info
           writing pip-egg-info/psycopg2.egg-info/PKG-INFO
           writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
           writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
           writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
           Error: could not determine PostgreSQL version from '10.1'
           
           ----------------------------------------
       Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-aip8f60z/psycopg2/
 !     Push rejected, failed to compile Python app.
 !     Push failed
`
I ran this one with psycopg2>=2.6.1 and I've tried a couple of others so I'm starting to doubt, appearances to the contrary, that this is really a psycopg2 issue. Anyway, I'm really looking for general advice at this point since I'm a Heroku novice (2 days experience!). I have got the python-getting-started and php-getting-started apps to work.

**Comment by GabLeRoux** [comment]
ok well maybe you can have a look at the differences between current project setup and the one you are trying.

according to error message, I think it does detect a postgresql installation but psycopg2 can’t figure out its version, it says it doesn’t know 10.1.

you may try to confirm postgresql is actually bundled in heroku. You may also seek for help directly on psycopg2 repos (as it’s unrelated to current swagger project).

you can also verify if it’s possible to bundle a slightly lower version of postgresql on heroku, I didn’t check how you can do this.

You may also try this locally or inside a virtual machine or maybe on a different cloud provider to see if you hit the same walls. Maybe you’ll have a better understanding of what’s going on. I know recent versions of psycopg2 were supposed to fix this 10.1 version detection error, I’m sure you can find the exact issue on the psycopg2 github repos. I’m not near a computer right now so I can’t help, but I’m sure you’ll figure it out.

Good luck 👍 

ps; if you can’t manage to get postgresql to work, you can always switch to mysql which may be easier to setup, but I personally think you’ll be much happier with postgres :). sqlite would require file storage is not there on heroku by default if I remember well (unless you enable some addon).

**Comment by rsedger** [comment]
Thanks @GabLeRoux - I had no idea we could specify MySQL on Heroku. I noticed with the PHP getting started Heroku tutorial the database was provisioned after the app was pushed to Heroku so I'm wondering about that. Anyway I now have more questions to ask and you've given some insights. I will push on, and thanks again.

**Comment by Smithmayowa20** [comment]
TThanks @GabLeRoux  it works with psycopg2==2.7.1
